### ISSUE TITLE
Fix the getMedian() method of MathBasics class for odd length inputs.

### ISSUE THREAD

**Issue by suresh-gandhi** [fossasia/neurolab-desktop#3]
**Actual Behaviour**
getMedian() method in MathBasics class doesn't give the correct answer for an input array of odd length. Instead, it returns the (median + 1)th element after arranging the input in ascending order.

**Expected Behaviour**
The method should return the correct median values for all possible inputs.

The issue is essentially the same as [#35](https://github.com/fossasia/neurolab-android/issues/35) of neurolab-android and should be corrected in this repo as well.

**Would you like to work on the issue?**
I would like to work on this issue.

**Comment by suresh-gandhi** [comment]
@CloudyPadmal Shall I work on the issue?

**Comment by CloudyPadmal** [comment]
Sure @suresh-gandhi :+1:
