### ISSUE TITLE
Redundant if/else checks in NeuroUtils class

### ISSUE THREAD

**Issue by RohitJain1103** [fossasia/neurolab-desktop#4]
**Actual Behaviour**

'getHexLookUpTable' method in NeuroUtils class calculates range using a redundant if/else statement and multiple checks.

**Expected Behaviour**

The range value could be easily calculated as Math.abs(startVal - endVal) and thus there is no need for checking through if/else statement.

**Proposed changes**

```
float range = 0;
if (((startVal<0) && (endVal<0)) || ((startVal>0) && (endVal>0)))
	range = Math.abs(startVal - endVal);
else
	range = Math.abs(startVal) +  Math.abs(endVal); 
```
The above could be optimized to:-
```
float range = Math.abs(startVal - endVal); 
```

**Would you like to work on the issue?**

I would like to work on it.

**Comment by CloudyPadmal** [comment]
Yes @RohitJain1103 you may start :+1:
